services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=blog123!'
      - 'POSTGRES_USER=blog'
    ports:
      - '5000:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver:
      local
