spring.application.name: core-api
spring.profiles.active: local

spring:
  profiles:
    include:
      - db-core
      - logger
      - monitoring
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: test

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: live

