@siteId=018c8a91-8d9e-6d6d-0c52-304adce65ecc
@wtsId=018c8b5c-8126-5df4-924d-1fc27a5839b9
### wts 생성
POST {{host}}/api/v1/site/{{siteId}}/wts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "name"
}


### wts 조회
GET {{host}}/api/v1/site/{{siteId}}/wts/{{wtsId}}
Content-Type: application/json
Authorization: Bearer {{token}}
