spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      pool-name: core-db-pool
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/blog?serverTimezone=UTC
    username: blog
    password: blog123!
    hikari:
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

---
spring.config.activate.on-profile: dev

spring:
  datasource:
    url: jdbc:postgresql://${storage.database.core-db.url}
    username: ${storage.database.core-db.username}
    password: ${storage.database.core-db.password}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

---
spring.config.activate.on-profile: live

spring:
  datasource:
    url: jdbc:postgresql://${storage.database.core-db.url}
    username: ${storage.database.core-db.username}
    password: ${storage.database.core-db.password}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true