logging.config: classpath:logback/logback-spring.xml
---
spring.config.activate.on-profile: local
logging:
  level:
    '[com.example.blog]': DEBUG
    '[org.springframework.web.servlet]': debug # response, request 로그
    '[org.hibernate.type.descriptor.sql.BasicBinder]': trace # 쿼리 로그에서 바인딩 파라미터를 보기위해 설정
    '[org.hibernate.type]': trace
---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: live

